apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  labels:
    app: movie
spec:
  replicas: 4 # Number of instances to run
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie-container
        image: manojkrishnappa/movie:1
        ports:
        - containerPort: 8080 # Assuming your app is listening on port 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
          requests:
            memory: "128Mi"
            cpu: "0.25"
