apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie
  ports:
  - protocol: TCP
    port: 80 # External port to expose
    targetPort: 8080 # Internal container port
  type: LoadBalancer # Use NodePort or ClusterIP if not using LoadBalancer
